services:
  kafka:
    image: ${KAFKA_IMAGE:-apache/kafka:4.1.2}
    container_name: clicklake-kafka
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093,PLAINTEXT_HOST://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    ports:
      - "29092:29092"
    volumes:
      - kafka_data:/var/lib/kafka/data
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: clicklake-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

  server:
    build:
      context: ./server
    container_name: clicklake-server
    depends_on:
      - kafka
      - redis
    env_file:
      - ./server/.env
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_RAW_EVENTS: clicklake.events.raw
      KAFKA_ENABLED: "true"
      COLLECT_DIRECT_RAW_ENABLED: "false"
      COLLECT_REQUIRE_KAFKA_PUBLISH: "true"
      WEB_CONCURRENCY: "4"
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
    restart: unless-stopped

  consumer:
    build:
      context: ./consumer
    container_name: clicklake-consumer
    depends_on:
      - kafka
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:9092
      KAFKA_TOPIC_RAW_EVENTS: clicklake.events.raw
      KAFKA_CONSUMER_GROUP: clicklake-consumer
      KAFKA_AUTO_OFFSET_RESET: earliest
      KAFKA_ENABLE_RAW_SINK: "true"
      KAFKA_SINK_DIR: /data/raw_events_kafka
      SINK_MAX_EVENTS_PER_FILE: "1000"
      KAFKA_ENABLE_BRONZE_DIRECT: "true"
      KAFKA_BRONZE_SINK_DIR: /data/bronze_batches_kafka
      KAFKA_BRONZE_MAX_EVENTS_PER_FILE: "1000"
    volumes:
      - ./server/data:/data
    restart: unless-stopped

  dashboard:
    build:
      context: ./dashboard
    container_name: clicklake-dashboard
    depends_on:
      - server
    environment:
      VITE_API_BASE_URL: http://localhost:8000
      VITE_DEV_PROXY_TARGET: http://server:8000
    ports:
      - "5173:5173"
    volumes:
      - ./dashboard:/app
      - /app/node_modules
    restart: unless-stopped

volumes:
  kafka_data:
  redis_data:
