apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clicklake-consumer-data
  namespace: clicklake
  labels:
    app.kubernetes.io/name: clicklake
    app.kubernetes.io/component: consumer
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
