apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: clicklake-redis-data
  namespace: clicklake
  labels:
    app.kubernetes.io/name: clicklake
    app.kubernetes.io/component: redis
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
